core/urls.py
from django.urls import path
from core import views

app_name = "todo"

urlpatterns = [
    path('create/', views.create_task, name="create"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('status/<int:id>', views.change_status, name="status"),
    path('delete/<int:id>', views.delete_task, name="delete"),
    path('detail/<int:id>', views.detail_task, name="detail"),
    path('update/<int:id>', views.update_task, name="update"),
    path('', views.list_task, name="list"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    OPTIONS = [
        ('pending', "Pending"),
        ('completed', "Completed")
        ]

    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250, blank=True, null=True)
    status = models.CharField(max_length=10, choices = OPTIONS, default="pending")
    created_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(blank=True, null=True)
    owner = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )
    
    def __str__(self):
        return self.title

core/forms.py
from django import forms 
from core.models import Task
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'title', 'description'
        )
        widgets = {
            "title" : forms.TextInput(
                attrs={"class" : "text-field", "max_length":50}),

            "description" : forms.Textarea(
                attrs={"class" : "text-area-field","cols" : 60, "rows":5})
            }
    

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username","first_name", "email", "password1", "password2"
        )
        widgets = {
            "username": forms.TextInput(
                attrs={
                    'placeholder': "username",
                    'class': 'field-register-input'
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    'placeholder': "name",
                    'class': 'field-register-input'
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    'placeholder': "email",
                    'class': 'field-register-input'
                }
            )
        }
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        # Adiciona atributos personalizados aos campos de senha
        self.fields['password1'].widget.attrs.update({
            'placeholder': 'password',
            'class': 'field-register-input'
        })
        self.fields['password2'].widget.attrs.update({
            'placeholder': 'confirm password',
            'class': 'field-register-input'
        })

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from core.forms import CreateTaskForm, UserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages, auth
from core.models import Task
from django.utils import timezone

# Create your views here.
def list_task(request):
    tasks = Task.objects.filter(owner=request.user).order_by('-id')
    context = {
        "tasks" : tasks
    }

    return render(
        request=request,
        template_name= "todo/list_task.html",
        context=context
        )

def create_task(request):

    if request.method == "POST":
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.owner = request.user
            task.save()
            messages.success(request=request, message="Task created sucessfully")
            return redirect('todo:create')
    else:
        form = CreateTaskForm()

    context = {"form": form}
    return render(
        request=request,
        template_name="todo/create_form.html",
        context=context
        )


def change_status(request, id):

    task= get_object_or_404(klass=Task, pk=id)
    task.status = "completed"
    task.finished_at = timezone.now()
    task.save()
    return redirect('todo:list')

def delete_task(request,id):
    task= get_object_or_404(klass=Task, pk=id)
    task.delete()
    return redirect('todo:list')


def detail_task(request, id):
    task= get_object_or_404(klass=Task, pk=id)
    context = {
        "task" : task
    }

    return render(
        request=request,
        template_name= "todo/detail_task.html",
        context=context
        )

def update_task(request, id):

    task= get_object_or_404(klass=Task, pk=id)

    if request.method == "POST":
        form = CreateTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request=request, message="Task updated sucessfully")
            return redirect('todo:list')
    else:
        form = CreateTaskForm(instance=task)

    context = {"form": form,
               "task": task}
    return render(
        request=request,
        template_name="todo/update_task.html",
        context=context
        )


def register(request):
    
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request=request, message="User registered!")
            return redirect("todo:list")

    else:
        form = UserForm()

    return render(
        request=request,
        template_name= "todo/register.html",
        context= {
            'form':form
        }

    )


def login(request):

    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request=request, user=user)
            messages.success(request=request, message="successfully logged in!")
            return redirect("todo:list")

    else:    
        form = AuthenticationForm(request=request)

    return render(
        request=request,
        template_name="todo/login.html", 
        context= {
        "form" : form
        }
    )
    
def logout(request):
    auth.logout(request)
    return redirect("todo:login")

core/templates/todo/create_form.html
{% extends "global/base.html" %}

{% block content %}

   
    <form class="form-container" action="{% url "todo:create" %}" method="POST">
        
        {% csrf_token %}
        <div class="field-container">
            <legend class="task-list-header">Create your task</legend>
            {% for field in form %} 
                
                <div class="input-container">
                    <label class="label-input" for="{{field.id_for_label}}">
                        {{field.label}}:
                    </label> 
                    {{field}}
                </div>
                {% if field.errors %}
                    <div class="field-errors input-container">
                        {{field.errors}}
                    </div>
                {% endif %}
            {% endfor %}
            
            {% if form.non_field_errors %}    
                <div class="message error ">
                    {{form.non_field_errors}}
                </div>
            {% endif %}
                
            <button class="submit-button" type="submit">Submit</button>
        </div>
    </form>
{% endblock content %}

core/templates/todo/detail_task.html
{% extends "global/base.html" %}

{% block content %}
    <div class="main-container">
        <h1 class="task-list-header">{{task.title}}</h1>
        <div class="details-container">
            <div class="detail-field"> Description:
                <p class="detail-paragraph">{{task.description}}</p>
            </div>
            <div class="detail-field"> Status:
                <p class="detail-paragraph">{{task.status}}</p>
            </div>
            <div class="detail-field"> Create at:
                <p class="detail-paragraph">{{task.created_at}}</p>
            </div>
            <div class="detail-field"> Finished at:
                {% if task.finished_at %}
                    <p class="detail-paragraph">{{task.finished_at}}</p>
                {% else %}
                    <p class="detail-paragraph">In progress</p>
                {% endif %}
            </div>
            <div class="detail-field container-button">
                <div class="button-update">
                    <a class="link-update" href="{% url "todo:update" task.id %}">Update</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/todo/list_task.html
{% extends "global/base.html" %}

{% block content %}

    <h1 class="task-list-header">Tasks</h1>
    {% if request.user.is_authenticated  %}
        <div class="greetings-user">
            <p>{{request.user}}'s tasks!</p>
        </div>
    {% endif %}
    {% if tasks %}
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th class="table-cel tbl-hd">Task</th>
                    <th class="table-cel tbl-hd">Status</th>
                    <th class="table-cel tbl-hd">Created at</th>
                    <th class="table-cel tbl-hd">Fineshed at</th>
                    <th class="table-cel tbl-hd action">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td class="table-cel shadow">
                            <a class="link-detail " href="{% url "todo:detail" task.id %}">{{task.title}}</a>
                        </td>
                        <td class="table-cel">
                            {% if task.status == "pending" %}
                               {{task.status}} 
                            {% else %}
                                <div class="finished_at">{{task.status}}</div> 
                            {% endif %}
                        </td>                   
                        <td class="table-cel">
                            {{task.created_at}}
                        </td>
                        <td class="table-cel">
                            {% if task.finished_at %}
                                {{task.finished_at}}
                            {% else %}
                                In progress
                            {% endif %}
                        </td>
                        <form action=""></form>
                        <td class="table-cel">
                            {% if task.status == "pending" %}
                                <a class="button-status" href="{% url "todo:status" task.id %}">&#10004;</a>
                            {% endif %}
                            <a class="button-status del" href="{% url "todo:delete" task.id %}">&#10008;</a>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    <div>
    {% else %}
        <div class="no-task-container">
            <div class="no-task-info">
                <p>No tasks to do!</p>
            </div>
        </div>
    {% endif %}   
{% endblock content %}

core/templates/todo/login.html
{% extends "global/base.html" %}

{% block content %}

    <form class="form-container" action="{% url "todo:login" %}" method="POST">
        
        {% csrf_token %}
        <div class="field-container-register">
            <legend class="task-list-header">Login</legend>
            {% for field in form %} 
                
                <div class="input-container">
                    <label class="label-input-register" for="{{field.id_for_label}}">
                        {{field.label}}:
                    </label> 
                    {{field}}
                </div>
                {% if field.errors %}
                    <div class="field-errors input-container">
                        {{field.errors}}
                    </div>
                {% endif %}
            {% endfor %}
            {% if form.non_field_errors %}    
                <div class="message error ">
                    {{form.non_field_errors}}
                </div>
            {% endif %}
            <div class="input-container">  
                <button class="submit-button-register" type="submit">Submit</button>
            </div>  
        </div>
    </form>

{% endblock content %}

core/templates/todo/register.html
{% extends "global/base.html" %}

{% block content %}

   
    <form class="form-container" action="{% url "todo:register" %}" method="POST">
        
        {% csrf_token %}
        <div class="field-container-register">
            <legend class="task-list-header">Register</legend>
            {% for field in form %} 
                
                <div class="input-container">
                    <label class="label-input-register" for="{{field.id_for_label}}">
                        {{field.label}}:
                    </label> 
                    {{field}}
                </div>
                    
                {% if field.errors %}
                    <div class="field-errors input-container">
                        {{field.errors}}
                    </div>
                {% endif %}
            {% endfor %}

            {% if form.non_field_errors %}    
                <div class="message error ">
                    {{form.non_field_errors}}
                </div>
            {% endif %}
            <div class="input-container">  
                <button class="submit-button-register" type="submit">Submit</button>
            </div>  
        </div>
    </form>
{% endblock content %}

core/templates/todo/update_task.html
{% extends "global/base.html" %}

{% block content %}
    <form class="form-container" action="{% url "todo:update" task.id %}" method="POST">
        {% csrf_token %}
        <div class="field-container">
            {% for field in form %}
                <div class="input-container">
                    <label class="label-input" for="{{field.id_for_label}}">
                        {{field.label}}:
                    </label> 
                    {{field}}
                    {{field.error}}
                </div>
            {% endfor %}
                
            <button class="submit-button" type="submit">Submit</button>
        </div>
    </form>
{% endblock content %}